filme/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from .views import (
    Homepage,
    Homefilme,
    Detalhefilme,
    Pesquisarfilmes,
    Editarperfil,
    Criaconta,
)

app_name = 'filme'
urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilme.as_view(), name='homefilme'),
    path('filmes/<int:pk>', Detalhefilme.as_view(), name='detalhesfilmes'),
    path('pesquisa/', Pesquisarfilmes.as_view(), name='pesquisarfilme'),
    path('criaconta/', Criaconta.as_view(), name='criaconta'),
    path(
        'login/',
        auth_view.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path(
        'logout_/',
        auth_view.LogoutView.as_view(template_name='logout.html'),
        name='logout',
    ),
    path(
        'editarperfil/<int:pk>',
        Editarperfil.as_view(template_name='editar_perfil.html'),
        name='editar_perfil',
    ),
    path(
        'alterasenha/',
        auth_view.PasswordChangeView.as_view(
            template_name='editar_perfil.html',
            success_url=reverse_lazy('homefilmes'),
        ),
        name='alterasenha',
    ),
]

legratube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

LISTA_CATEGORIAS = (
    ('FILME', 'Filme'),
    ('SERIE', 'Série'),
    ('MUSICA', 'Musica'),
    ('CURSO', 'Curso'),
    ('OUTROS', 'Outros'),
)
# Create your models here.
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.titulo


class Episodio(models.Model):
    filme = models.ForeignKey(
        'Filme', related_name='episodio', on_delete=models.CASCADE
    )
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self) -> str:
        return self.filme.titulo + ' - ' + self.titulo


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField('Filme')

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class HomepageForm(forms.Form):
    email = forms.EmailField(label=False)


class Criarcontaform(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
"""Views do django."""
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import Criarcontaform, HomepageForm
from .models import Filme, Usuario

# Create your views here.
class Homepage(FormView):
    template_name = 'homepage.html'
    form_class = HomepageForm

    def get(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse:
        if request.user.is_authenticated:
            return redirect('filme:homefilme')
        return super().get(request, *args, **kwargs)

    def get_success_url(self) -> str:
        email = self.request.POST.get('email')
        usuario = Usuario.objects.filter(email=email)
        if usuario:
            return reverse('filme:login')
        return reverse('filme:criaconta')


class Homefilme(LoginRequiredMixin, ListView):
    template_name = 'homefilmes.html'
    model = Filme


class Detalhefilme(LoginRequiredMixin, DetailView):
    template_name = 'detalhesfilmes.html'
    model = Filme

    def get(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse:
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super(Detalhefilme, self).get_context_data(**kwargs)
        filmes_relacionado = Filme.objects.filter(
            categoria=self.get_object().categoria
        )[0:4]
        context['filmes_relacionados'] = filmes_relacionado
        return context


class Pesquisarfilmes(LoginRequiredMixin, ListView):
    template_name = 'pesquisarfilmes.html'
    model = Filme

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(
                titulo__icontains=termo_pesquisa
            )
            return object_list
        else:
            return None


class Editarperfil(LoginRequiredMixin, UpdateView):
    template_name = 'editar_perfil.html'
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self) -> str:
        return reverse('filme:homefilme')


class Criaconta(FormView):
    template_name = 'criaconta.html'
    form_class = Criarcontaform

    def form_valid(self, form: Any) -> HttpResponse:
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('filme:login')

filme/templates/criaconta.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Criar Conta
{% endblock %}
{% load crispy_forms_tags %}
{% block head %}
<style>
    #hint_id_username,
    #hint_id_password1,
    #hint_id_password2 {
        color: lightblue!important;
    }
    @media screen and  (max-width: 550px){
        .conta{
            max-width: 80%!important;
        }
    }
</style>
{% endblock %}

{% block content%}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-center bg-fixed bg-cover"  style="background-image: url('{% static 'images/netflix-fundo.jpg' %}');">
    <div class="conta z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form | crispy}}
                <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
        </form>

    </div>
</header>
{% endblock %}

filme/templates/detalhesfilmes.html
{% extends 'base.html' %}

{% block titulo %}
{{ object.titulo }}
{% endblock %}

{% block head %}
<style>
@media screen and  (max-width: 400px){
        .filme {
            width: 100%!important;
        }
    }
</style>
{% endblock %}

{% block content %}
<main class="min-h-screen w-full">
    <section
        class="h-screen relative bg-fixed pb-8 pl-6 flex items-end bg-cover bg-center bg-black bg-opacity-50 bg-blend-overlay"
        style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-4xl sm:text-6xl font-semibold text-white my-4">
                {{ object.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":150" }}...
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-zinc-50 hover:bg-red-500 py-2 px-5 rounded-md" style="color:black;">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class="bg-primary_black flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left items-center min-w-full">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>
            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios
                </h2>
                {% if not object.episodios.all %}
                <h3 class="text-lg">
                    Em breve
                </h3>
                {% else %}
                {% for episodio in object.episodios.all %}
                <h3 class="text-lg">
                    <a href="{{ episodio.video }}">
                        <p>{{ forloop.counter }} - {{ episodio.titulo }}</p>
                    </a>
                </h3>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
    {% if filmes_relacionados %}
    <section class="flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center justify-center min-w-full">
                {% for filme in filmes_relacionados %}
                <div class="flex flex-col">
                    <div class="filme flex flex-col m-4 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="hover:scale-110 transition ease-in-out object-cover w-full h-full" alt="">
                        </a>
                    </div>
                    <p style="color: whitesmoke; ">{{filme.titulo}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
</main>
{% endblock %}

filme/templates/editar_perfil.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Login
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<header
    class="min-h-screen min-w-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-center bg-fixed bg-cover"
    style="background-image: url('{% static 'images/netflix-fundo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form | crispy}}
            </fieldset>
            <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Altera
            </button>
        </form>
        <small>
            Quer alterar senha?
            <p>
                <a href="{% url 'filme:alterasenha' %}" class="text-yellow-300">
                    Clique aqui para alterar a senha
                </a>
            </p>
        </small>
    </div>
</header>
{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
Homefilmes
{% endblock %}
{% block head %}
<style>
  html {
    scroll-behavior: smooth;
  }

  body {
    margin: 0;
    background-color: #000;
  }

  h1 {
    font-family: Arial;
    color: red;
    text-align: center;
  }

  .wrapper {
    display: grid;
    grid-template-columns: repeat(3, 100%);
    overflow: hidden;
    scroll-behavior: smooth;
  }

  .wrapper section {
    width: 100%;
    position: relative;

    .item {
      padding: 0 0px;
      transition: 250ms all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }
    }
  }

  .wrapper section a {
    color: #fff;
    text-decoration: none;
    font-size: 6em;
    background: rgb(0, 0, 0);

    &:nth-of-type(1) {
      top: 0;
      bottom: 0;
      left: 0;
      background: linear-gradient(
        -90deg,
        rgba(0, 0, 0, 0) 0%,
        rgba(0, 0, 0, 1) 100%
      );
    }
    &:nth-of-type(2) {
      top: 0;
      bottom: 0;
      right: 0;
      background: linear-gradient(
        90deg,
        rgba(0, 0, 0, 0) 0%,
        rgba(0, 0, 0, 1) 100%
      );
    }
  }

  @media only screen and (max-width: 600px) {
    a.arrow__btn {
      display: none;
    }
  }
</style>
{% endblock %} {% block content %}
<main class="bg-primary_black min-h-screen w-full">
  <section
    class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover"
    style="background-image: url('{{filme_destaque.thumb.url}}')"
  >
    <div>
      <h2 class="text-6xl font-semibold text-white my-4"></h2>
      {{filme_destaque.titulo}}
      <p class="w-11/12 md:w-5/12 font-medium text-white my-4"></p>
      {{filme_destaque.descricao |slice:":150" }}
      <div class="flex my-4">
        <a href="{% url 'filme:detalhesfilmes' filme_destaque.pk %}">
          <button
            class="flex items-center bg-white py-2 px-5 rounded-md"
            style="color: black"
          >
            <ion-icon name="play" class="text-2xl"></ion-icon>
            <span class="ml-3 font-medium"> Play </span>
          </button>
        </a>
      </div>
    </div>
  </section>

  <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Novo</h2>
      <div class="wrapper">
        <section
          id="section1"
          class="flex flex-nowrap items-center justify-center space-x-8"
        >
          <a href="#section2" class="arrow__btn text-6xl page">‹</a>
          {% for filme in lista_filmes_recente %}
            {% if forloop.counter < 5 %}
            <div class="item h-64 w-1/4 m-4">
              <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                <img
                  src="{{filme.thumb.url}}"
                  class="rounded-md h-full w-full object-cover"
                />
              </a>
            </div>
            {% endif %}
          {% endfor %}

          <a href="#section2" class="arrow__btn text-6xl">›</a>
        </section>
        {% if lista_filmes_recente|length > 4 %}
          <section
            id="section2"
            class="flex flex-nowrap items-center justify-center"
          >
            <a href="#section1" class="arrow__btn text-6xl">‹</a>
            {% for filme in lista_filmes_recente %}
              {% if forloop.counter > 4 %}
                <div class="item h-64 w-1/4 m-4">
                  <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                    <img
                      src="{{filme.thumb.url}}"
                      class="rounded-md w-full h-full object-cover"
                    />
                  </a>
                </div>
              {% endif %}
            {% endfor %}

            <a href="#section1" class="arrow__btn text-6xl">›</a>
          </section>
        {% endif %}
      </div>
    </div>
  </section>

  <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Em alta</h2>
      <div class="wrapper">
        <section
          id="section1emalta"
          class="flex flex-nowrap items-center justify-center space-x-8"
        >
          <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
          {% for filme in lista_filmes_alta %}
            {% if forloop.counter < 5 %}
            <div class="item h-64 w-1/4 m-4">
              <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                <img
                  src="{{filme.thumb.url}}"
                  class="rounded-md w-full h-full object-cover"
                />
              </a>
            </div>
            {% endif %}
          {% endfor %}

          <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
        </section>
        
        {% if lista_filmes_alta|length > 4 %}
        <section
          id="section2emalta"
          class="flex flex-nowrap items-center justify-center"
        >
          <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
          {% for filme in lista_filmes_alta %}
          {% if forloop.counter > 4 %}
          <div class="item h-64 w-1/4 m-4">
            <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
              <img
                src="{{filme.thumb.url}}"
                class="rounded-md w-full h-full object-cover"
              />
            </a>
          </div>
          {% endif %} {% endfor %}
          <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
        </section>
        {% endif %}
      </div>
    </div>
  </section>

  <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Continuar assistindo</h2>
      <div class="wrapper">
        <section
          id="section1vistos"
          class="flex flex-nowrap items-center justify-center space-x-8"
        >
          <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
          {% for filme in request.user.filmes_vistos.all %}
          {% if forloop.counter < 5 %}
          <div class="item h-64 w-1/4 m-4">
            <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
              <img
                src="{{filme.thumb.url}}"
                class="rounded-md w-full h-full object-cover"
              />
            </a>
          </div>
          {% endif %} {% endfor %}
          <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
        </section>
        {% if request.user.filmes_vistos.all|length > 4 %}
        <section
          id="section2vistos"
          class="flex flex-nowrap items-center justify-center"
        >
          <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
          {% for filme in request.user.filmes_vistos.all %}
            {% if forloop.counter > 5 %}
            <div class="item h-64 w-1/4 m-4">
              <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
                <img
                  src="{{filme.thumb.url}}"
                  class="rounded-md w-full h-full object-cover"
                />
              </a>
            </div>
            {% endif %}
          {% endfor %}
          <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
        </section>
        {% endif %}
      </div>
    </div>
  </section>
</main>

{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% block title %}
homepage
{% endblock %}
{% block head %}
<style>
    #id_email{
        color: black;
        width: 100%;
        padding: 5px 5px;
    }
</style>
{% endblock %}
{% block content %}
{% load static %}
<header class="min-h-screen min-w-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-center bg-fixed bg-cover" style="background-image: url('{% static 'images/netflix-fundo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes, séries e muito mais, sem limites
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="justify-center">
                    {% csrf_token %}
                    <div class="flex flex-grow items-stretch gap-2 align-center">
                        {{ form }}
                        <button
                            class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl"
                            type="submit">
                            <span>
                                Vamos Lar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Aproveite na sua TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Assista em Smart Tvs, Playstation, Xbox, Chrmecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Baixe suas séries e filmes favoritos para assistir onde quiser.
        </h2>
        <h5 class="md:text-xl text-lg">
            É possível assistir seus downloads até mesmo offline.
        </h5>
    </div>

</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Crie contas para crianças.
        </h2>
        <h5 class="md:text-xl text-lg">
            Garanta que suas crianças tenham uma aventura mágica e sem conteúdos violentos ou impróprios.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/netkids.png' %}" class="w-8/12" alt="">
    </div>
</section>
{% endblock %}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Login
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<header
    class="min-h-screen min-w-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-center bg-fixed bg-cover"
    style="background-image: url('{% static 'images/netflix-fundo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form | crispy}}
                <legend class="border-bottom mb-4">Faça login para continuar</legend>
            </fieldset>
            <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer
                Login
            </button>
        </form>
        <small>
            Não tem uma conta ainda? 
            <p>
                <a href="{% url 'filme:criaconta' %}" class="text-yellow-300">
                    Clique aqui para criar uma conta
                </a>
            </p>
        </small>
    </div>
</header>
{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-cover bg-center bg-fixed"  style="background-image: url('{% static 'images/netflix_fundo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">Logout realizado com sucesso!</h2>
        <div class="flex flex-nowrap justify-center space-x-5 p-5">
        <a href="{% url 'filme:login' %}"><button class="bg-red-600  py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>
        <a href="{% url 'filme:criaconta' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>
        </div>
    </div>
</header>
{% endblock %}

filme/templates/pesquisarfilmes.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de filmes 
{% endblock %}

{% block content %}
<main class="bg-primary_black min-h-screen w-full">
  <section class="bg-primary_black min-h-screen flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Resultados da Busca</h2>
      <div class="flex flex-wrap items-center min-w-full movie_lis">
        {% if object_list%}        
          {% for filme in object_list%}
          <div
          class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96"
        >
          <a href="{% url 'filme:detalhesfilmes' filme.pk %}">
            <img
              src="{{filme.thumb.url}}"
              class="object-cover w-full h-full"
              alt=""
            />
          </a>
        </div>
          {% endfor %}
        {% else %}
        <p>nada encontrdo</p>
        {% endif%}
      </div>
    </div>
  </section>
</main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}    
    </title>
    {% block head %}
    {% endblock %}   
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navegacao.html'%}
    {% block content %}
    {% endblock %}
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center text-xs sm:text-sm">
            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
        </ul>
    </footer>
    <script>
         const nav = document.querySelector('nav');

    document.addEventListener('scroll', e => {
        if (scrollY > 80) {
            if (scrollY > window.innerHeight) {
            nav.classList.add('invisible');
            } else {
            nav.classList.add('bg-gray-900');
            nav.classList.remove('invisible');
            }
        } else {
            nav.classList.remove('bg-gray-900');
            nav.classList.remove('invisible');
        }
    });
    </script>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/navegacao.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img src="{% static 'images/logo.png'%}" class="">
        </a>
    </div>
    <div class="w-6/12 flex flex-row gap-2 justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'filme:pesquisarfilme' %}">
                <input name="query" type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar">
                <input type="submit" value="">
            </form>
        </div>
        
        <div class="mr-2">
            <a href="{% url 'filme:editar_perfil' user.pk %}">
                <button class=" bg-red-600 text-white py-1 px-3 rounded-md">Editar Perfil</button>
            </a>
        </div>
        <form method="post" action="{% url 'filme:logout' %}">
            {% csrf_token %}
            <button type="submit" class="mr-2 bg-red-600 text-white py-1 px-3 rounded-md">Sair</button>
        </form>        
        {% else %}
        <div class="mr-2">
            <a href="{% url 'filme:login' %}">
                <button class=" bg-red-600 text-white py-1 px-3 rounded-md">Login</button>
            </a>
        </div>
        {% endif %}
    </div>
</nav>